# NumPy Arrays

## Загрузка библиотеки

In [1]:
import numpy as np

## Python List

In [2]:
list_ = [1, 2, 3]

In [8]:
arr = np.array(list_)

In [9]:
arr

array([1, 2, 3])

In [10]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in

### arange

In [12]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [16]:
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones(3)

array([1., 1., 1.])

In [18]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### linspace

In [21]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [22]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

In [23]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

### rand

In [25]:
np.random.rand(5)

array([0.7571348 , 0.4478043 , 0.01619527, 0.70300363, 0.18702272])

In [27]:
np.random.rand(5, 3)

array([[0.38011802, 0.93387914, 0.30741093],
       [0.05579608, 0.89174969, 0.76451471],
       [0.91842534, 0.5918365 , 0.99151676],
       [0.87892323, 0.4539997 , 0.66988554],
       [0.49240518, 0.30208529, 0.12203989]])

### randn

In [28]:
np.random.randn(2)

array([0.1502022 , 1.43325241])

In [29]:
np.random.randn(5,3)

array([[ 0.65510753,  0.77862173, -0.19950529],
       [ 0.35011908,  0.45516947, -2.90048213],
       [ 0.15380448,  0.74930362, -0.66413255],
       [-0.0727424 ,  0.98452027,  1.10187884],
       [ 0.52369472, -1.39537471,  0.57014391]])

### randint

In [30]:
np.random.randint(1,100)

65

In [31]:
np.random.randint(1,100,10)

array([31, 41, 94, 71, 15, 20, 73, 15, 84, 77])

## Array Attributes and Methods

In [32]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
ranarr

array([ 3, 14, 25, 31, 45,  6, 41, 34, 32, 10])

### Reshape

In [48]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

In [40]:
ranarr.max()

45

In [41]:
ranarr.min()

3

In [42]:
ranarr.argmax()

4

In [43]:
ranarr.argmin()

0

### Shape

In [44]:
arr.shape

(25,)

In [49]:
arr = arr.reshape(1, 25)

In [50]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [51]:
arr.shape

(1, 25)

In [52]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [53]:
arr.reshape(25,1).shape

(25, 1)

In [54]:
arr.dtype

dtype('int32')