# NumPy common

## Load libraries

In [1]:
import pandas as pd
import numpy as np

## Load data

In [2]:
df = pd.read_csv("../../data/in/credit_cart_data.csv")
df.head()

person_index  SeriousDlqin2yrs  RevolvingUtilizationOfUnsecuredLines  age  \
0             1                 1                              0.766127   45   
1             2                 0                              0.957151   40   
2             3                 0                              0.658180   38   
3             4                 0                              0.233810   30   
4             5                 0                              0.907239   49   

   NumberOfTime30-59DaysPastDueNotWorse  DebtRatio  MonthlyIncome  \
0                                     2   0.802982         9120.0   
1                                     0   0.121876         2600.0   
2                                     1   0.085113         3042.0   
3                                     0   0.036050         3300.0   
4                                     1   0.024926        63588.0   

   NumberOfOpenCreditLinesAndLoans  NumberOfTimes90DaysLate  \
0                               13                        0   
1                                4                        0   
2                                2                        1   
3                                5                        0   
4                                7                        0   

   NumberRealEstateLoansOrLines  NumberOfTime60-89DaysPastDueNotWorse  \
0                             6                                     0   
1                             0                                     0   
2                             0                                     0   
3                             0                                     0   
4                             1                                     0   

   NumberOfDependents  
0                 2.0  
1                 1.0  
2                 0.0  
3                 0.0  
4                 0.0

## numpy

In [3]:
np.log?

Call signature:  np.log(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'log'>
File:            e:\projects_for_job\data-science-pandas-plotly-ml\ds-ppml_env\lib\site-packages\numpy\__init__.py
Docstring:      
log(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Natural logarithm, element-wise.

The natural logarithm `log` is the inverse of the exponential function,
so that `log(exp(x)) = x`. The natural logarithm is logarithm in base
`e`.

Parameters
----------
x : array_like
    Input value.
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At l

In [4]:
np.log(10, dtype=np.float64)

2.302585092994046

In [5]:
np.log(10, dtype=np.float16)

2.303

In [6]:
np.log(10, dtype=np.float32)

2.3025851

In [7]:
np.log(0.)

C:\Users\guyze\AppData\Local\Temp\ipykernel_9024\2773519477.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(0.)


-inf

In [8]:
print(np.log10(10))
print(np.log10(100))

1.0
2.0


In [9]:
np.round(4.5), np.floor(4.5), np.ceil(4.5), np.int8(4.5)

(4.0, 4.0, 5.0, 4)

In [10]:
np.round(-4.5), np.floor(-4.5), np.ceil(-4.5), np.int8(-4.5)

(-4.0, -5.0, -4.0, -4)

In [11]:
# переполнение!
np.power(2, 1000), type(np.power(2, 1000))

(0, numpy.int32)

In [12]:
2 ** 1000, type(2 ** 1000) # the same, only through Python

(10715086071862673209484250490600018105614048117055336074437503883703510511249361224931983788156958581275946729175531468251871452856923140435984577574698574803934567774824230985421074605062371141877954182153046474983581941267398767559165543946077062914571196477686542167660429831652624386837205668069376,
 int)

In [13]:
np.cos(np.pi)

-1.0

In [14]:
np.e

2.718281828459045

## ndarray

In [15]:
a = np.array([1, 2, 3, 1, 0])
type(a)

numpy.ndarray

In [16]:
a

array([1, 2, 3, 1, 0])

In [17]:
print(a)
print("a.shape = ", a.shape)
print("a.ndim =", a.ndim)
print("a.size =", a.size)
print("a.dtype =", a.dtype)
print("Размер каждого элемента массива в байтах a.itemsize =", a.itemsize)
print("Обращение к элементу a[0] =", a[0])

[1 2 3 1 0]
a.shape =  (5,)
a.ndim = 1
a.size = 5
a.dtype = int32
Размер каждого элемента массива в байтах a.itemsize = 4
Обращение к элементу a[0] = 1


In [18]:
b = np.array([[1, 8, 3], 
              [3, 2, 1], 
              [3, 5, 6]])

In [19]:
print(b)
print("a.shape = ", b.shape)
print("a.ndim =", b.ndim)
print("a.size =", b.size)
print("a.dtype =", b.dtype)
print("Размер каждого элемента массива в байтах a.itemsize =", b.itemsize)
print("Нулевая строка b[0] =", b[0])
print("Обращение к элементу b[строка][столбец]: b[0][1] =", b[0][1])
print("Обращение к элементу b[строка, столбец]: b[0, 1] =", b[0, 1])

[[1 8 3]
 [3 2 1]
 [3 5 6]]
a.shape =  (3, 3)
a.ndim = 2
a.size = 9
a.dtype = int32
Размер каждого элемента массива в байтах a.itemsize = 4
Нулевая строка b[0] = [1 8 3]
Обращение к элементу b[строка][столбец]: b[0][1] = 8
Обращение к элементу b[строка, столбец]: b[0, 1] = 8


## array creation

In [20]:
m = np.array([[1, 8, 3], 
              [3, 2, 1], 
              [3, 5, 6]])
print(m)

[[1 8 3]
 [3 2 1]
 [3 5 6]]


In [21]:
m = np.eye(3)
print(m)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
m = np.eye(N=3, M=4)
print(m)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [23]:
m = np.ones((5, 4))
print(m)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [24]:
m = np.ones(5)
print(m)
print(m.shape)
print(type(m[1]))

[1. 1. 1. 1. 1.]
(5,)
<class 'numpy.float64'>


In [25]:
m = np.zeros((1, 4), dtype=int)
print(m)
print(m.shape)
print(m.ndim)

[[0 0 0 0]]
(1, 4)
2


In [26]:
v = np.zeros(4)
print(v)

[0. 0. 0. 0.]


In [27]:
m = np.arange(0, 10, 2)
print(m)
m = np.arange(10)
print(m)

[0 2 4 6 8]
[0 1 2 3 4 5 6 7 8 9]


In [28]:
m = np.zeros((5, 5))
m += np.arange(5)
print(m)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [29]:
m = np.linspace(0, 3, 4)
print(m)

[0. 1. 2. 3.]


- создание массива из диапазона [$base^{start}$, $base^{end}$]

In [30]:
m = np.logspace(2.0, 5.0, num=4, base=2.0)
print(m)

[ 4.  8. 16. 32.]


## random

In [31]:
np.random.seed(42)

In [32]:
# равномерное (uniform) распределение [0, 1)
print(np.random.rand(2, 2))
print(np.random.rand(2, 2).shape)

[[0.37454012 0.95071431]
 [0.73199394 0.59865848]]
(2, 2)


In [33]:
np.random.randn(2, 3, 2)

array([[[ 1.57921282,  0.76743473],
        [-0.46947439,  0.54256004],
        [-0.46341769, -0.46572975]],

       [[ 0.24196227, -1.91328024],
        [-1.72491783, -0.56228753],
        [-1.01283112,  0.31424733]]])

In [34]:
# массив из случайно выбранных чисел
# size - размер возвращаемого массива, reaplce=False без замещения
np.random.choice(a=np.arange(20), size=5, replace=False)

array([13, 10,  5,  7, 17])

In [35]:
np.random.choice(a=np.arange(20), size=(2, 3), replace=True)

array([[ 8,  1, 19],
       [14,  6, 11]])

## Time

In [41]:
%%time
a = list(range(10 ** 6))

CPU times: total: 31.2 ms
Wall time: 49 ms


In [40]:
%%time
a_numpy = np.arange(10 ** 6)

CPU times: total: 0 ns
Wall time: 2 ms


In [42]:
%%time
for idx, elem in enumerate(a):
    a[idx] = elem * 2

CPU times: total: 296 ms
Wall time: 326 ms


In [44]:
%%time
b = np.arange(1, 10 ** 6 + 1, dtype=np.float64)
b = b * 2

CPU times: total: 93.6 ms
Wall time: 92 ms


## Index

In [45]:
m = np.array([[1, 8, 3], 
              [3, 2, 1], 
              [3, 5, 6]])
print(m)

[[1 8 3]
 [3 2 1]
 [3 5 6]]


In [46]:
m[2]

array([3, 5, 6])

In [47]:
m[2, :]

array([3, 5, 6])

In [48]:
m[:, 1]

array([8, 2, 5])

### submatrix

In [49]:
m[[0, 2], [0]]

array([1, 3])

In [50]:
m[[0, 2], [0, 1, 2]]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (3,) 

In [51]:
m[np.ix_([0, 2], [0, 1, 2])]

array([[1, 8, 3],
       [3, 5, 6]])

## Matrix Operations

In [52]:
m = np.array([[1, 12, 3, 4], 
              [3, 2, 10, 2], 
              [3, 56, 6, 11]])
print(m)
print()
print(m.T)

[[ 1 12  3  4]
 [ 3  2 10  2]
 [ 3 56  6 11]]

[[ 1  3  3]
 [12  2 56]
 [ 3 10  6]
 [ 4  2 11]]


### Dot product of vectors

In [53]:
a = np.array([3, 1, 5, 2])
b = np.array([2, 5, 2, 4])
# <a, b> = 3*2 + 1*5 + 5*2 + 2*4
print(a @ b)    # python 3 style
print(a.dot(b)) 
print(np.dot(a, b))

29
29
29


### Matrix multiplication

In [54]:
a = np.array([[1, 2], [0, 1]])
b = np.array([[4, 1], [2, 2]])
print(a @ b)
print(a.dot(b)) 
print(np.dot(a, b))

[[8 5]
 [2 2]]
[[8 5]
 [2 2]]
[[8 5]
 [2 2]]


### ПОКООРДИНАТНОЕ умножение

In [55]:
print(a * b)

[[4 2]
 [0 2]]


### Умножение матриц и векторов

In [56]:
m = np.array([[1, 2], [0, 1], [2, 4]])
print(m)
v = np.array([2, 5])
print("v = ",v)

[[1 2]
 [0 1]
 [2 4]]
v =  [2 5]


In [57]:
m @ v

array([12,  5, 24])

## Useful Functions and Methods

In [59]:
print(a, b, sep='\n\n')

[[1 2]
 [0 1]]

[[4 1]
 [2 2]]


In [60]:
np.log(b)

array([[1.38629436, 0.        ],
       [0.69314718, 0.69314718]])

In [61]:
np.sin(a)

array([[0.84147098, 0.90929743],
       [0.        , 0.84147098]])

In [62]:
a = np.random.choice(a=np.linspace(1, 50, 50), size=10, replace=False)
print(a)

[42.  5. 41. 44. 11. 46.  3. 39. 48. 12.]


### Замена элементов по индексу

In [64]:
np.put(a, ind=[0, 2], v=[-44, -55, -66])
a

array([-44.,   5., -55.,  44.,  11.,  46.,   3.,  39.,  48.,  12.])

### Выделение элементов по условию

In [65]:
np.where(a < 0, -1, 1)

array([-1,  1, -1,  1,  1,  1,  1,  1,  1,  1])

In [66]:
a[np.where(a < 0)]

array([-44., -55.])

In [69]:
a[a < 0]

array([-44., -55.])

### Sort

In [67]:
np.sort(a)

array([-55., -44.,   3.,   5.,  11.,  12.,  39.,  44.,  46.,  48.])

### Индексы сортированного массива

In [68]:
np.argsort(a)

array([2, 0, 6, 1, 4, 9, 7, 3, 5, 8], dtype=int64)

In [70]:
m = np.round(np.random.rand(4, 5) * 10, 3)
print(m)

[[7.713 0.74  3.585 1.159 8.631]
 [6.233 3.309 0.636 3.11  3.252]
 [7.296 6.376 8.872 4.722 1.196]
 [7.132 7.608 5.613 7.71  4.938]]


In [71]:
# сортировка по столбцам
np.sort(m, axis=0)

array([[6.233, 0.74 , 0.636, 1.159, 1.196],
       [7.132, 3.309, 3.585, 3.11 , 3.252],
       [7.296, 6.376, 5.613, 4.722, 4.938],
       [7.713, 7.608, 8.872, 7.71 , 8.631]])

In [72]:
# сортировка по строкам
np.sort(m, axis=1)

array([[0.74 , 1.159, 3.585, 7.713, 8.631],
       [0.636, 3.11 , 3.252, 3.309, 6.233],
       [1.196, 4.722, 6.376, 7.296, 8.872],
       [4.938, 5.613, 7.132, 7.608, 7.71 ]])

### Cортировка всех столбцов по первому столбцу:

In [73]:
np.random.seed(21)
a = np.random.randint(0, 10, (5, 3))
print(a)
print()
print(a[a[:,1].argsort()])

[[9 8 4]
 [0 0 8]
 [3 2 1]
 [8 9 6]
 [0 4 6]]

[[0 0 8]
 [3 2 1]
 [0 4 6]
 [9 8 4]
 [8 9 6]]


## newaxis

In [74]:
a = np.linspace(1, 10, 10)
print(a)
print(a.shape)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
(10,)


In [75]:
print(a[:, np.newaxis])
print("New shape ", a[:, np.newaxis].shape)

[[ 1.]
 [ 2.]
 [ 3.]
 [ 4.]
 [ 5.]
 [ 6.]
 [ 7.]
 [ 8.]
 [ 9.]
 [10.]]
New shape  (10, 1)


In [76]:
m = np.random.randint(0, 10, (5, 10))

In [78]:
m

array([[4, 4, 7, 8, 9, 5, 6, 5, 2, 6],
       [2, 8, 2, 0, 5, 5, 0, 3, 0, 8],
       [1, 0, 2, 6, 4, 9, 0, 0, 5, 5],
       [9, 6, 3, 4, 6, 9, 0, 0, 0, 9],
       [5, 2, 9, 7, 1, 8, 2, 7, 8, 9]])

In [79]:
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [77]:
m @ a

array([300., 183., 200., 220., 349.])

In [80]:
m @ a[:, np.newaxis]

array([[300.],
       [183.],
       [200.],
       [220.],
       [349.]])

In [81]:
a.shape

(10,)

In [84]:
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [85]:
m = a.reshape((5, 2, 1, 1))
print(m)
print('------------------------')
print(m[..., np.newaxis, np.newaxis].shape)
print('------------------------')
print(m[:, np.newaxis, np.newaxis])
print("New shape ", m[:, np.newaxis, np.newaxis].shape)

[[[[ 1.]]

  [[ 2.]]]


 [[[ 3.]]

  [[ 4.]]]


 [[[ 5.]]

  [[ 6.]]]


 [[[ 7.]]

  [[ 8.]]]


 [[[ 9.]]

  [[10.]]]]
------------------------
(5, 2, 1, 1, 1, 1)
------------------------
[[[[[[ 1.]]

    [[ 2.]]]]]




 [[[[[ 3.]]

    [[ 4.]]]]]




 [[[[[ 5.]]

    [[ 6.]]]]]




 [[[[[ 7.]]

    [[ 8.]]]]]




 [[[[[ 9.]]

    [[10.]]]]]]
New shape  (5, 1, 1, 2, 1, 1)


## any, all

In [86]:
any([True, True, False, True, False, False, False])

True

In [87]:
all([True, True, False, True, False, False, False])

False

In [88]:
np.array([1, 1, 0, 2]) == np.array([1, 1, 0, 2])

array([ True,  True,  True,  True])

In [89]:
all(np.array([1, 1, 0, 0]) == np.array([1, 1, 0, 2]))

False

In [90]:
any(np.array([1, 1, 0, 0]) == np.array([1, 1, 0, 2]))

True

In [91]:
a = (np.array([1, 1, 0, 8, 1, 5, 1, 1]) == np.array([1, 1, 3, 2, 1, 5, 1, 1])).reshape((2, 4))
print(a)

[[ True  True False False]
 [ True  True  True  True]]


In [92]:
# string
a.any(axis=1)

array([ True,  True])

In [93]:
# column
a.any(axis=0)

array([ True,  True,  True,  True])

In [94]:
# string and column
a.all((0, 1))

False

## diff

In [95]:
a = np.array([1, 2, 4, 7, 0])
print(a)
print(np.diff(a))

[1 2 4 7 0]
[ 1  2  3 -7]


## split

In [96]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [97]:
np.split(a, [2, 7])

[array([0, 1]), array([2, 3, 4, 5, 6]), array([7, 8, 9])]

## Computing statistics

In [98]:
a = np.random.randint(-10, 70, (5, 4))
print(a)

[[54 15 68 37]
 [29 -5 33  8]
 [29 -6 24 40]
 [47  6 -9 41]
 [-9 17 23 22]]


In [99]:
a.mean()

23.2

In [100]:
# column
a.mean(axis=0)

array([30. ,  5.4, 27.8, 29.6])

In [101]:
# string
a.mean(axis=1)

array([43.5 , 16.25, 21.75, 21.25, 13.25])

### median

In [102]:
print(np.median(a))
print(np.median(a, axis=0))
print(np.median(a, axis=1))

23.5
[29.  6. 24. 37.]
[45.5 18.5 26.5 23.5 19.5]


## max min

In [103]:
print(a.max())
print(a.max(axis=0))
print(a.argmax(axis=0))
print(a.max(axis=1))
print(a.argmax(axis=1))

68
[54 17 68 41]
[0 4 0 3]
[68 33 40 47 23]
[2 2 3 0 2]


### counter

In [104]:
np.bincount(np.arange(5))

array([1, 1, 1, 1, 1], dtype=int64)

In [105]:
np.bincount(np.array([0, 1, 1, 3, 2, 1, 7]))

array([1, 3, 1, 1, 0, 0, 0, 1], dtype=int64)

In [106]:
sub_sums = np.bincount(np.array([2, 0, 2, 1, 0, 0, 2, 2, 0, 1]), 
                        weights=[4, 4, 2, 3, 5, 1, 6, 1, 7, 5])

# 0 -> 4 + 5 + 1 + 7 = 17
# 1 -> 3 + 5 = 8
# 2 -> 4 + 2 + 6 + 1 = 13
print(sub_sums)

[17.  8. 13.]


In [107]:
z = np.random.randint(0, 10, 50)
print(z)
print(np.bincount(z).argmax())

[2 6 9 1 3 1 1 1 1 1 6 5 7 5 4 6 1 9 1 3 6 8 1 9 1 0 9 8 3 9 4 0 2 9 0 8 1
 1 4 6 8 5 0 3 5 7 0 8 5 3]
1
